### ISSUE TITLE
Still seeing IMDb ratings

### ISSUE THREAD

**Issue by DrexlSpivey** [Dem1se/hide-ratings-extension-firefox#8]
Chrome still hides them. I don't see them in my list:

![image](https://github.com/nithssh/hide-ratings-extension-firefox/assets/102897859/88f17eab-4226-4954-b92f-992be2db45b7)

But I see them after opening a specific entry:

![image](https://github.com/nithssh/hide-ratings-extension-firefox/assets/102897859/7c989ec2-9242-4cda-aeea-c3cefc0c6388)

**Comment by specificocean23** [comment]
I have the same issue! except I'm on firefox. tried reinstalling but nothing.

**Comment by nithssh** [comment]
Hey guys, sorry for the late reply, I was not aware. The issue is due to this fork not being up to date with chrome.I have made a new release that is directly based on the chrome extension.

 This fork is no longer required and further releases will be directly based on the original chrome repo. Thanks for reporting the issue, and please report any further ones at the upstream repo

Thanks and sorry for being a bad maintainer.
